# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
plugins:
  - rubocop-elegant
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
Naming/FileName:
  Regex: '^[a-z0-9\-._]*$'
Style/GlobalVars:
  Enabled: false
Style/TopLevelMethodDefinition:
  Enabled: false
Elegant/GoodMethodName:
  Enabled: false
Elegant/GoodVariableName:
  Enabled: false
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 2
Style/RedundantException:
  Enabled: false
