# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
plugins:
  - rubocop-elegant
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
Naming/FileName:
  Regex: '^[a-z0-9\-._]*$'
