# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: make
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  make:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ruby/setup-ruby@6e5d382445ae5590b7449d8b3bc8cb1c2c27f617 # v1.317.0
        with:
          ruby-version: 4.0
          bundler-cache: true
      - run: sudo apt-get update && sudo apt-get install -y parallel
      - run: make
