# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: rake
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  rake:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1.312.0
        with:
          ruby-version: 4.0.5
          bundler-cache: true
      - run: bundle config set --global path "$(pwd)/vendor/bundle"
      - run: bundle install --no-color
      - run: bundle exec rake
