# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: up
'on':
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  up:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: ./.github/actions/update-version
        with:
          owner: ${{ github.repository_owner }}
          repo: judges-action
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          sign-commits: true
          branch: version-up
          commit-message: 'new version in README'
          delete-branch: true
          title: 'New version in README'
          base: master
