# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: xcop
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  xcop:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: xcop
        run: docker run --rm -v ${{ github.workspace }}:/work ruby:3.2-alpine@sha256:d206c25708a44df6a7ce22213ee5da9fc0a9f7b31ce884429ba758db48abdc62 sh -c "gem install xcop -v 0.9.0 && xcop /work"
