# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: yamllint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  yamllint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
